- name: Ensure a SSH key is present
  tags: sshkey
  digital_ocean:
    state=present
    command=ssh
    name="{{ my_ssh_key }}"
    ssh_pub_key='ssh-rsa ...'
    api_token="{{ mytoken }}"
  register: ssh_id
  run_once: true

- debug: msg="SSH_KEY_ID is {{ ssh_id.ssh_key.id }}"

- name: Create droplet in DigitalOcean
  tags: droplet
  digital_ocean:
    state=present
    command=droplet
    unique_name=yes
    id="{{ did }}"
    name="{{ dname }}"
    ssh_key_ids="{{ ssh_id.ssh_key.id }}"
    api_token="{{ mytoken }}"
    image_id="{{ image }}"
    size_id="{{ size }}"
    region_id="{{ region }}"
    wait_timeout=500
  register: my_droplet
  run_once: true

- add_host: name={{ my_droplet.droplet.ip_address }} groupname=launched-dc

- debug: msg="ID is {{ my_droplet.droplet.id }}"
- debug: msg="IP is {{ my_droplet.droplet.ip_address }}"

- name: Wait for SSH to come up
  wait_for: host={{ my_droplet.droplet.ip_address }} port=22 delay=30 timeout=360 state=started
